### ISSUE TITLE
Some messages get skipped

### ISSUE THREAD

**Issue by Ingvix** [paul-nameless/tg#186]
I'm not sure if it's just after the first time message fetch that causes this but when browsing message history in my chats some messages are skipped and the selection goes to the one after the skipped line. In the logs the current-msg shows that the selection only moved a single message like the skipped one doesn't exist at all from the programs perspective.

**Comment by paul-nameless** [comment]
Thanks for the report.
It is known problem and should be fixed.
I'll have a closer look when have time.

**Comment by matheusfillipe** [comment]
This is still happening. Once you select up to a message that is above the pane height, when it has to scroll up, then it starts selecting every 2 until you go to the bottom again. Very annoying problem actually.
